### ISSUE TITLE
Restrictions on deployment of contracts

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-sdk#23]
Question with regards to rate at which one can deploy a contract to evernode.

If I find a bug that causes the node I've deployed to to crash. What's stopping me from deploying that same contract across every node?

Assume there needs to be some gate keeping there, so say how often and across how many nodes a contract can be deployed. Though, I could just slightly alter it and then deploy it on others.

Something that jumped in my head after exploring here a little to night.

**Comment by wojake** [comment]
Your contract is limited to the docker instance's resources, everything and anything that happens in your contract (which includes the node) will be contained in the docker instance. The host (sashimono) will not be affected in any way.

You can deploy as many contracts as you wish on Evernode, as long as there's enough nodes to facilitate your demands.

**Comment by wojake** [comment]
https://github.com/HotPocketDev/evernode-sdk/blob/main/evernode/tutorial-basics.md

**Comment by lathanbritz** [comment]
perfect!
