### ISSUE TITLE
Global Clock (PAXOS)

### ISSUE THREAD

**Issue by wojake** [HotPocketDev/evernode-sdk#24]
PAXOS is a complicated thing to code, I doubt that most devs would be able to integrate a global clock in their contracts.
Implementing a global clock (via PAXOS) in the contract lib as a function would be best moving forward `Time()`. 

Since time is a critical component in distributed systems, and since contracts are basically standalone L1 blockchains, this needs to be implemented.

**Comment by chalith** [comment]
We already have an underlying capability to support this. Check this tutorial https://github.com/HotPocketDev/evernode-sdk/blob/main/hotpocket/tutorial-npl.md

**Comment by wojake** [comment]
Thank you!
