### ISSUE TITLE
(Hook/Host) Security issue with usage of Ledger Sequence

### ISSUE THREAD

**Issue by wojake** [HotPocketDev/evernode-sdk#28]
Since hosts are using ledger sequence (we're presuming that 1190 ledgers = 1 hour), there might be an issue when the ledger halts or slows down. If the ledger halts or slows down majorly, hosts will still be hosting contracts without getting paid or in a case where the ledger progress slows down: Their payment is delayed.

There are a few solutions being considered.

(Post for backtracking purposes, resolving w/ Richard & Ravin)

**Comment by chalith** [comment]
We've started resolving this issue.

**Comment by ravinsp** [comment]
@wojake We have narrowed down the implementation approach for this.
- "Moment" is going be redefined as real-world 1 hour. This will affect the contract expiration logic in Sashimono as well as the reward schedule of the hook.
- We will consider contract "creation time" to be when the contract spin up completed on the host machine. (We will not use any timestamp from the ledger)
- Under normal circumstances, contracts will be expired according to real-world time duration spent from their creation time.
- If Sashimono thinks xrpledger has halted or slowed down, it will not expire any contracts during that period.
- When the xrpledger is back online, contracts will still not get expired until a grace period (we think the grace period will be decided based on how long xrpl was down)
- There are additional considerations for when the hook needs to be gracefully "transitioned" from old logic to new logic, but I won't go into detail here.

**Comment by chalith** [comment]
Closing the issue since the resolution is discussed
