### ISSUE TITLE
TypeScript env file

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-sdk#31]
does the .env file get deployed along with the rest of the js project files?
<img width="1774" alt="Screen Shot 2022-10-13 at 00 10 43" src="https://user-images.githubusercontent.com/508629/195490387-56bac8a0-b721-454a-8b50-43c3f4cf52ce.png">

**Comment by lathanbritz** [comment]
not sure how to handle certain things here. My assumption was putting sensitive information into a .env that is then deployed with the node instances into the hp/docker instance? How would / should I go about handling that.

**Comment by chalith** [comment]
You can pass environment variables via HotPocket config's `contract.environment` field https://github.com/HotPocketDev/evernode-sdk/blob/main/hotpocket/reference-configuration.md#contract. Which you can pass through the `hp.cfg.override` file inside the `dist` directory.

**Comment by lathanbritz** [comment]
rocking thank you!

**Comment by lathanbritz** [comment]
I assume to load them im going to need to dig inside the 'HotPocket.Contract' instance ?

const hpc = new HotPocket.Contract();
hpc.init(myContract);

**Comment by lathanbritz** [comment]
ah i just found code doing it

```
        const hpconfig = await ctx.getConfig();
        // Wait only for half of roundtime.
        const timeoutMs = Math.ceil(hpconfig.consensus.roundtime / 2);
```

got what i need thanks again.

**Comment by lathanbritz** [comment]
<img width="1960" alt="Screen Shot 2022-10-13 at 10 19 44" src="https://user-images.githubusercontent.com/508629/195607834-afc711a3-c774-4bf2-a98f-fdc022ecc620.png">
<img width="1003" alt="Screen Shot 2022-10-13 at 10 20 13" src="https://user-images.githubusercontent.com/508629/195607866-4f2461a3-c8d6-4fba-9a32-77fdec000bfc.png">


nope still struggling on loading those variables back out.

**Comment by lathanbritz** [comment]
<img width="1144" alt="Screen Shot 2022-10-13 at 10 23 32" src="https://user-images.githubusercontent.com/508629/195608538-d8b9872c-1cc1-460a-b7e9-459cad48a5ac.png">
issue seems to be its not uploading the config... notice environment is empty there and it seems to be nested inside another environment

**Comment by chalith** [comment]
> <img alt="Screen Shot 2022-10-13 at 10 19 44" width="1960" src="https://user-images.githubusercontent.com/508629/195607834-afc711a3-c774-4bf2-a98f-fdc022ecc620.png">
> 
> <img alt="Screen Shot 2022-10-13 at 10 20 13" width="1003" src="https://user-images.githubusercontent.com/508629/195607866-4f2461a3-c8d6-4fba-9a32-77fdec000bfc.png">
> 
> nope still struggling on loading those variables back out.

@lathanbritz you need to pass them like `environment: 'VAR1=1 VAR2=2'`. Then you can access it as `process.env.VAR1` `process.env.VAR2`

**Comment by wojake** [comment]
That's a weird way tbh, can't we change it and match @lathanbritz's variable placement?

**Comment by lathanbritz** [comment]
that is a little strange but i can work with that for now.

+1 to alter that to use key value pair as ive tried, as allows objects and arrays to be passed string may be to limiting.

**Comment by lathanbritz** [comment]
still not working for me so far
<img width="2234" alt="Screen Shot 2022-10-14 at 18 56 59" src="https://user-images.githubusercontent.com/508629/195950108-09aa2d38-a3ed-41d5-9202-ff27fa97ab6d.png">

**Comment by lathanbritz** [comment]
There is a typo in one of the strings...

environment and enviroment are both used.


```
hpconfig.enviroment {
  version: '1.0',
  unl: [
    'ed3970a1f1eeb8c7b1861144840420c84b1573b7c7afbece93b2accfbcf2e1f24f',
    'eda1fe5812a52ca65b5c203ddf4a71d610cf4b3c5fc2d0e04ee3f9d2efa545f03d',
    'edb16352136f3b28fc69e14e62350aaaf70638381daed67f0eeb832d81f7ac4835'
  ],
  bin_path: '/usr/bin/node',
  bin_args: 'index.js',
  environment: '',
  max_input_ledger_offset: 10,
  consensus: { mode: 'private', roundtime: 1000, stage_slice: 25, threshold: 80 },
  npl: { mode: 'private' },
  round_limits: {
    user_input_bytes: 0,
    user_output_bytes: 0,
    npl_output_bytes: 0,
    proc_cpu_seconds: 0,
    proc_mem_bytes: 0,
    proc_ofd_count: 0
  }
}
```

**Comment by ravinsp** [comment]
@lathanbritz I think the typo `enviroment` comes from your own override config as I can see from your screenshot showing key/value pairs.

We also think key/value pair is better than the current format. We will consider this for upcoming improvement.

Regarding the "sensitive" nature of the values, I think you cannot consider this like a regular application because all the smart contract files (including the config) is deployed to the host. The host has full access to these files so any sensitive information in your contract code or config files could be leaked.

**Comment by lathanbritz** [comment]
@ravinsp how is the best way to handle sensitive information, in this case? I chose working through this example as it was going to be one of my questions.

**Comment by ravinsp** [comment]
@lathanbritz Well, you have to figure that out yourself based on your specific use case. There are no generic solutions here. Whatever you decide to place on a decentralized network could be seen by somebody else. Evernode is no exception. In this case, you are intending to deploy your code/files on several other hosts which are owned by other people. Each host has complete control over on what's deployed on itself.

For your specific use case on submitting XRPL transactions from a HotPocket contract, the answer is using [XRPL multi sig](https://xrpl.org/set-up-multi-signing.html) and distributing the quorum keys among individual smart contract instances. In the future, we intend to come up with "recipes" or libraries which can help you do this. But for now, you have to DYOR.

**Comment by lathanbritz** [comment]
Even if one goes multi sig the keys for that signature go with the contract... I'm confused as how that helps here.

Or is it just accepted that the quorum key is exposed. But simply relies upon having those distributed and needing x keys to sign to meet quorum?

**Comment by lathanbritz** [comment]
Ah apparently I need to have the instance sign the transaction across them. I simply need to add those as multi sig to the wallet. Where is the doc to do that?

**Comment by wojake** [comment]
I'll write an Issue up, resolving w/ lathan. Again, I don't think there's such function for that right now on any hotpocket library, I've checked

**Comment by ravinsp** [comment]
@lathanbritz yes, each individual quorum key will be "exposed" to the host that instance is deployed on. The protection comes from all quorum members having to sign the transaction. After that the contract instances have to coordinate among themselves to collect all quorum signatures and submit the final transaction. See https://xrpl.org/send-a-multi-signed-transaction.html

@wojake is right. Our libraries do not contain any XRPL multisig helpers yet. But in the future, we intend to include them to support contract developers who wants to integrate with XRPL. Until then any solutions you try out yourself will help the community.

**Comment by wojake** [comment]
https://github.com/HotPocketDev/evernode-sdk/issues/34: This issue should close if this is fine.

**Comment by lathanbritz** [comment]
Right I've played with the example of the advanced NPL. That makes a lot of sense when having to have a single instance send a tx. For me I will be using that random logic to pick a node to be creating the signed TX that will be sent to the XRPL.


I would really like to see a contract with how one should be handling key's ie. I wan to see how one should be submitting a transaction and having the contracts multi sign. As even if i make it a multi sig requirement on the final submitted transaction. All key pairs would then need to be in the enviroment variables that go into the deployed contract.. so all keys would be know.... 

sorry im struggling to pick up how this "should" be done here and hence asking for possibly a code example.

**Comment by lathanbritz** [comment]
Aaaah wait I think the penny finally dropped for me.

So I will simply be creating a new wallet on each contract instance.

I then with external client query each contract for their public keys.

From that I then compose the multi signature list on the 'main/shared wallet'.

Then I never need keys in the environment vars.

🙃 took me a little but I got there I think.

Sorry for all the questions.

**Comment by ravinsp** [comment]
Closing this issue since environment variable specific issue has been addressed.
