### ISSUE TITLE
Trans compile side effects

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-sdk#32]
<img width="1137" alt="Screen Shot 2022-10-15 at 21 10 02" src="https://user-images.githubusercontent.com/508629/196011999-dc40cb22-b7bf-4e6a-9229-1c5d52f2ddeb.png">

<img width="612" alt="Screen Shot 2022-10-15 at 21 05 40" src="https://user-images.githubusercontent.com/508629/196011922-89a64761-4592-4e74-a85f-17b82a1db0b5.png">

` Cannot construct STArray from value given`

this is following the standard format from XRPL-Labs lib to sign a transaction https://gist.github.com/WietseWind/557a5c11fa0d474468e8c9c54e3e5b93

also less important there seems to be another transcompile issue with the buffer from...

`const Memos =  {
                    Memo: {
                        MemoData: Buffer.from(JSON.stringify(data.rawResultsNamed), 'utf-8').toString('hex').toUpperCase(),
                        MemoFormat: Buffer.from('text/csv', 'utf-8').toString('hex').toUpperCase(),
                        MemoType: Buffer.from('rates:' + JSON.stringify(data.rawResults), 'utf-8').toString('hex').toUpperCase()
                    }
                }`

**Comment by lathanbritz** [comment]
here is a link to the contract im building as exorcise. https://github.com/lathanbritz/mycontract/blob/master/src/mycontract.js

**Comment by ravinsp** [comment]
Thanks @lathanbritz. Can you try the same code without any hotpocket stuff and run it as a standalone nodejs app? (like `node src/mycontract.js`)

I initially suspected that this could be an issue with the vercel/ncc build that hpdevkit is using. But when I just ran your xrpl transaction code without ncc build, I got the same STArray error.

It's a good idea to write your application logic and test it out in a separate code file, so you can run it independently of HotPocket. This way when you encounter issues like this, you can verify whether it's a "normal" issue or something to do with HotPocket easily.
