### ISSUE TITLE
 DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-sdk#35]
I initially thought this was an issue at https://github.com/WietseWind/xrpl-accountlib/issues/308 however after finally figuring out how to dump the stack trace https://stackoverflow.com/a/50432372 
<img width="1396" alt="Screen Shot 2022-10-17 at 23 26 13" src="https://user-images.githubusercontent.com/508629/196321355-3d00eb79-a05b-4d6d-9fd4-f7c58f66865e.png">
and then scanning the generated code this issue it produced from the trans compile... with in Evernode its self.
<img width="1639" alt="Screen Shot 2022-10-17 at 23 26 29" src="https://user-images.githubusercontent.com/508629/196321366-9cc47bc9-b87d-46e5-b99c-c97356c3ed28.png">

**Comment by lathanbritz** [comment]
simplest way to reproduce this is add the line

`const lib = require('xrpl-accountlib')`

to the top of your contract and add the package via yarn/npm

even though 'xrpl-accountlib' is void of using Buffer() directly.

is will then start printing the Buffer warning..

**Comment by chalith** [comment]
Warning seems to be coming from `ripple-secret-codec` which is a dependency of `xrpl-accountlib`. Constructing buffer with `new Buffer([33])` is now deprecated as the warning says. But it's used that way in `ripple-secret-codec`

**Comment by lathanbritz** [comment]
Thank you @chalith

**Comment by WietseWind** [comment]
https://github.com/WietseWind/xrpl-accountlib/issues/308#issuecomment-1284585280
