### ISSUE TITLE
Deploying contract ~ tecINSUFFICIENT_FUNDS

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-sdk#40]
returning `Transaction result: tecINSUFFICIENT_FUNDS` `Tenant received acquire error:  TRANSACTION_FAILURE`

can check i do have EVRs issued to r4DosiqK2PYcemac4ySY9B8VXP8aRzABbP  https://hooks-testnet-v2-explorer.xrpl-labs.com/r4DosiqK2PYcemac4ySY9B8VXP8aRzABbP/lines

following ... https://github.com/HotPocketDev/evernode-sdk/blob/main/evernode/tutorial-basics.md 

```
   let instanceName;
   try {
      const result = await tenantClient.acquireLease(pickedHost.address, {
         owner_pubkey: "ed1cac2eadcd4272e4d61ab7db9e2af2469b9a5c174d86a97056cf000db7863219", // Replace the public key you've received in Step 3
         contract_id: "dc411912-bcdd-4f73-af43-32ec45844b9a",
         image: "hp.latest-ubt.20.04-njs.16",
         config: {}
      });
      console.log('Tenant received instance ', result.instance);
      instanceName = result.instance.name;
   }
   catch (err) {
      console.log("Tenant received acquire error: ", err.reason);
   }
```

**Comment by ravinsp** [comment]
@lathanbritz I see the following trustline in your tenant account. It says balance 0.
```
{
  account: "rfxLPXCcSmwR99dV97yFozBzrzpvCa2VCf",
  balance: "0",
  currency: "EVR",
  limit: "99999999",
  ...
}
```

Can you check the EVR balance after executing `giftBetaTenantEvr` transaction as mentioned in the tutorial. Not sure whether this is a bug in the gifting logic.

**Comment by lathanbritz** [comment]
<img width="1179" alt="Screen Shot 2022-10-23 at 00 42 39" src="https://user-images.githubusercontent.com/508629/197372531-29217288-78b5-4179-ba50-74fe176262ed.png">

**Comment by ravinsp** [comment]
@lathanbritz There was indeed an issue in our EVR gifting service. It had been corrected now. You can try again.

**Comment by lathanbritz** [comment]
worked now, thanks!
