### ISSUE TITLE
hpdevkit clean doesn't remove the `hpdevkit_default_net`

### ISSUE THREAD

**Issue by dangell7** [HotPocketDev/evernode-sdk#42]
If I go into the docker dashboard and clean everything I get this error when running `npm start`:

`Cluster 'default' already exists.`

If I do hpdevkit clean it does not remove the default network. I have to run `docker network prune` to remove the network.

**Comment by ravinsp** [comment]
If you manually tamper with docker resources created by hpdevkit it might throw errors when you run it next time. Instead, you should uninstall hpdevkit if you no longer want to use it.

`hpdevkit clean` would simply remove any container you have deployed your contract to. To remove all the resources created by hpdevkit you need to uninstall hpdevkit.
