### ISSUE TITLE
Are all contacts public?

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-sdk#44]
If I am looking to build a contract that I would like to charge a fee for someone to use. How would I keep the contact code private? Is this achievable here?

**Comment by ravinsp** [comment]
@lathanbritz No. Whatever you deploy to a host can be seen/reverse-engineered by that host. I don't think there's a way around it.

**Comment by wojake** [comment]
Won't be possible: It just makes the contract entirely centralized if you decide to maintain the cluster using your own nodes.

**Comment by lathanbritz** [comment]
the other work around is simply just injecting part of the algo a function from the client this is possibly a better work around here.

**Comment by ravinsp** [comment]
@lathanbritz whatever you do if it gets executed on the host, they could peek into what your code is doing. You can only make it more and more difficult with various tricks like code injection, encryption etc... If they are determined enough to sniff it out, you cannot prevent it fully.

As @wojake mentioned, if all the hosts/instances of your contract are owned by you then that makes it a centralized application.
